backend:
  name: git-gateway
  repo: shinoefuhi/shinoefuhi-site # ご自身のリポジトリ名に合わせてください
  branch: main

media_folder: "images/uploads" # 画像が保存される場所
public_folder: "/images/uploads"

collections:
  - name: "lives"
    label: "LIVE情報"
    folder: "_data/lives" # ライブデータを個別に保存する場所
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - label: "公演日"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        
     - label: "OPEN時間"
        name: "open_time"
        widget: "string"
        hint: "例：18:30"
        required: false

      - label: "START時間"
        name: "start_time"
        widget: "string"
        hint: "例：19:00"
        required: false

      - label: "チケット料金"
        name: "price"
        widget: "string"
        hint: "前売 ¥3,000 / 当日 ¥3,500 (+1D)"
        required: false
        
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "会場", name: "place", widget: "string"}
      
      - name: "artists"
        label: "共演"
        widget: "string"
        required: false
        
      - {label: "チケットURL", name: "ticketUrl", widget: "string", required: false}
      - {label: "フライヤー画像", name: "flyer", widget: "image", required: false}
  

  - name: "discography"
    label: "作品情報"
    folder: "_data/discography"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "種別", name: "type", widget: "select", options: ["Digital Single", "EP", "Album"]}
      - {label: "ジャケット画像", name: "image", widget: "image"}
      - {label: "Apple Music URL", name: "appleMusic", widget: "string", required: false}
      - {label: "Spotify URL", name: "spotify", widget: "string", required: false}
      - {label: "YouTube URL", name: "youtube", widget: "string", required: false}
      - {label: "CD詳細情報", name: "body", widget: "markdown", required: false}
