backend:
  name: github
  repo: shinoefuhi/shinoefuhi-site
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "lives"
    label: "Live Information"
    folder: "_data/lives"
    create: true
    slug: "{{date}}-{{title}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Place", name: "place", widget: "string", required: false }
      - { label: "Open Time", name: "open_time", widget: "string", required: false }
      - { label: "Start Time", name: "start_time", widget: "string", required: false }
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Artists", name: "artists", widget: "string", required: false }
      - { label: "Ticket URL", name: "ticketUrl", widget: "string", required: false }

  - name: "discography"
    label: "Discography"
    folder: "_data/discography"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image URL", name: "image", widget: "string" }
      - { label: "YouTube URL", name: "youtube", widget: "string", required: false }
      - { label: "Apple Music URL", name: "appleMusic", widget: "string", required: false }
      - { label: "Spotify URL", name: "spotify", widget: "string", required: false }
